### ISSUE TITLE
Inconsistent assertion messages that do not remove whitespaces

### ISSUE THREAD

**Issue by falsandtru** [power-assert-js/babel-plugin-espower#15]
https://travis-ci.org/twada/power-assert-keeper/jobs/129144771#L876-L877

**Comment by twada** [comment]
It's due to output format difference between `escodegen` and `babel-generator` and I do not guarantee trivial output consistency between babel-plugin-espower and other instrumentors.

**Comment by falsandtru** [comment]
I see, thanks.
