### ISSUE TITLE
Babel 7

### ISSUE THREAD

**Issue by cameron-martin** [power-assert-js/babel-plugin-espower#22]
Babel/babylon 7 (currently in beta) will be released soon. This plugin currently errors when compiling TypeScript files using babel 7:

```
ReferenceError: src\test.tests.ts: unknown node of type "TSAsExpression" with constructor "Node"
    at Generator.print (node_modules\babel-plugin-espower\node_modules\babel-generator\lib\printer.js:279:13)
```

Possibly it just needs it's babel dependencies updating and it might just work.

**Comment by twada** [comment]
@cameron-martin  Thank you for reporting!
babel-plugin-espower codebase is almost ready for Babel7 changes and waiting for GA of Babel7, but yeah, I must keep in touch. I'm going to update deps and fix failures.

**Comment by bj00rn** [comment]
@twada Babel 7 is out! Can we expect a release anytime soon?
