### ISSUE TITLE
3.0 release (Babel 7 compat)

### ISSUE THREAD

**Issue by bj00rn** [power-assert-js/babel-plugin-espower#26]
@twada Babel 7 is out!

Is the codebase compatible and can we expect a release anytime soon?

**Comment by twada** [comment]
@bj00rn Thank you for pinging me. [3.0.0](https://github.com/power-assert-js/babel-plugin-espower/blob/master/CHANGELOG.md#300-2018-08-30) has been released 🎉

**Comment by bj00rn** [comment]
@twada 🥇
