### ISSUE TITLE
Detecting the spread operator

### ISSUE THREAD

**Issue by novemberborn** [power-assert-js/babel-plugin-espower#28]
From https://github.com/avajs/ava/issues/2004:

```js
test("example1", t => {
  t.true(...[false, "bad!"]);
})
```

Currently this crashes. Implementing this fully seems like a stretch, but it'd be good if the plugin didn't crash.

**Comment by twada** [comment]
@novemberborn Thank you for reporting and finding edge case. Now I'm working on this issue.

**Comment by twada** [comment]
@novemberborn Fixed by #29 and released as [3.0.1](https://github.com/power-assert-js/babel-plugin-espower/blob/master/CHANGELOG.md#301-2019-01-08). Thank you for using and reporting 😃
