### ISSUE TITLE
I made a breaking change:

### ISSUE THREAD

**Issue by jamestalmage** [power-assert-js/babel-plugin-espower#8]
When I made [this change](https://github.com/power-assert-js/espower/commit/398585fd0cdc964089585d4b3e1eae2847f8d7da#diff-0c7eddb00dad6c27f01fa6d0917d6294R31), I thought I was modifying a private API.

Unfortunately AssertionVisitor is exposed publicly and [used in `babel-plugin-espower`](https://github.com/power-assert-js/babel-plugin-espower/commit/2a8389f513a0b58fd9f6a7adf88a42a2ce6d9a95#diff-24f9ae58e7bfba4a620542eda6fd8c46R34).

The only way this is a problem is if people have pinned to `babel-plugin-espower@>=1.0.0 <1.1.0` (i.e. a [Tilde Range](https://github.com/npm/node-semver#tilde-ranges-123-12-1))

It is probably worth releasing `babel-plugin-espower@1.0.4` that pins `espower@>=1.0.0 <=1.2.0`.

This probably has implications for `empower` as well.

**Comment by twada** [comment]
@jamestalmage Oh nice catch. I should be more aware of argument ordering.

Now working on 1.0.4 release.

**Comment by twada** [comment]
Released [babel-plugin-espower 1.0.1](https://github.com/power-assert-js/babel-plugin-espower/blob/master/CHANGELOG.md#101-2015-11-07). Thanks!
